# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [55]:
## import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

# input for weight
# input for height
# formula to get ans
# want user to only input a float num
# throw an angry message if not a num

# solve first lists, conditional if statement. then do inputs


def get_bmi():
    
    if weight == int(float(input())):
        weight = input()
    elif height == int(float(input())):
        height = input()
        formula = weight / (height**2) * 730
        return formula
    
    elif height or weight not  int(float(input())):
        print('¡Introduzca sólo números, por favor!')
        
    
print(get_bmi())
    
    
    
    
    
    
    
    
#     intweight = 0
# while True:
#     try:      
#         weight = float(input('weight: '))
#         height = float(input('height: '))
#         ans = weight / height**2 *730
# #     return ans
#         break
#     except ValueError:
#         print("PLEASE ENTER VALID NUMBEROS")
#     else:
#         break
# print(get_bmi())

SyntaxError: invalid syntax (<ipython-input-55-4c80fb5e73af>, line 27)

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [119]:
import numpy as np

"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass



#def random_matrix will take 2 params
# creates random matrix
#going to use random.uniforms for fun and store it in vars
#pass said vars into function
#gimme 3 numbers from 0 through 20
#gimme 3 nums from 2 through 10

# try to store num1 n num2 into a num 3 if error occurs
# with passing both num1 and num2 into randint
# I want to make the row and column randomly generated
# so Ill store random numbers in a var,
# then pass it in the randint, size












num1 = np.random.uniform(0,20,3)
num2 = np.random.uniform(2,10,3)

num_1 = np.random.uniform(1,5,5)
num_2 = np.random.uniform(1,5,5)



# a = [] not needed




def makeMatrix(low,high,shape,data_type = float):


    a = np.arange(low, high, 1, data_type)
    reshaped_a = a.reshape(shape)
    return reshaped_a

print(makeMatrix(0,16,(4,4),int))







# ------------------------------------------------------------------



# scrapped
# make arr in m randomized,
# along with random sumbers in each position
# so Ill set stuff in vars and pass em into a new var

# num1 = np.random.uniform(0,20,3)
# num2 = np.random.uniform(2,10,3)



# num_1 = np.random.uniform(1,5,5)
# num_2 = np.random.uniform(1,5,5)


# def generate_matrix(num_1,num_2):
#     M[:, num_1:num_2, :] = num_1
#     return M

# print(generate_matrix(num_1,num2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### #3 - Extra: step#1 Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons(Done). Step#2 Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [107]:
import csv
import numpy as np

#Test to make sure you have the correct data
#open, load, difference, slg?
def open_csv(filename, d = ','):
    # define an empty list to store data
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        # use the csv reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # Loop over info and append to data list
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../HW/files/redsox_2017_hitting.txt')
# csv_data = open_csv('../HW/files/redsox_2018_hitting.txt')

print(csv_data[:])

[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB'], ['1', 'C', 'Christian Vazquez', '26', '99', '345', '324', '43', '94', '18', '2', '5', '32', '7', '2', '17', '64', '.290', '.330', '.404', '.735', '91', '131', '14', '3', '0', '1', '0'], ['2', '1B', 'Mitch Moreland', '31', '149', '576', '508', '73', '125', '34', '0', '22', '79', '0', '1', '57', '120', '.246', '.326', '.443', '.769', '99', '225', '14', '6', '0', '5', '6'], ['3', '2B', 'Dustin Pedroia', '33', '105', '463', '406', '46', '119', '19', '0', '7', '62', '4', '3', '49', '48', '.293', '.369', '.392', '.760', '100', '159', '11', '2', '2', '4', '4'], ['4', 'SS', 'Xander Bogaerts', '24', '148', '635', '571', '94', '156', '32', '6', '10', '62', '15', '1', '56', '116', '.273', '.343', '.403', '.746', '95', '230', '17', '6', '0', '2', '6'], ['5', '3B', 'Rafael Devers', '20', '58', '240', '222', '34', '63', '

In [2]:
import csv
import numpy as np

#Test to make sure you have the correct data

def open_csv(filename, d = ','):
    # define an empty list to store data
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        # use the csv reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # Loop over info and append to data list
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../HW/files/redsox_2018_hitting.txt')

print(csv_data[1:5])

[['1', 'C', 'Sandy Leon', '29', '89', '288', '265', '30', '47', '12', '0', '5', '22', '1', '0', '15', '75', '.177', '.232', '.279', '.511', '37', '74', '6', '4', '3', '1', '0'], ['2', '1B', 'Mitch Moreland', '32', '124', '459', '404', '57', '99', '23', '4', '15', '68', '2', '0', '50', '102', '.245', '.325', '.433', '.758', '102', '175', '12', '0', '0', '5', '2'], ['3', '2B', 'Eduardo Nunez', '31', '127', '502', '480', '56', '127', '23', '3', '10', '44', '7', '2', '16', '69', '.265', '.289', '.388', '.677', '81', '186', '17', '2', '1', '3', '0'], ['4', 'SS', 'Xander Bogaerts', '25', '136', '580', '513', '72', '148', '45', '3', '23', '103', '8', '2', '55', '102', '.288', '.360', '.522', '.883', '135', '268', '14', '6', '0', '6', '4']]


In [6]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,27), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../HW/files/redsox_2017_hitting.txt')
bs2018 = load_data('../HW/files/redsox_2018_hitting.txt')

SLG_17 = bs2017['SLG']
SLG_18 = bs2018['SLG']

def diff(d1,d2):
    if d1.shape > d2.shape:
        print(d1)
        print('year 17 had more')
    else:
        print(d2)
        print('18 is was better')
diff(SLG_17, SLG_18)
# SLG_17_arr = np.array(SLG_17)
# SLG_18_arr = np.array(SLG_18)





[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
year 17 had more
